# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('color', models.CharField(max_length=200, verbose_name='Color')),
                ('image', models.ImageField(default=0, upload_to='static')),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Converse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('color', models.CharField(max_length=200, verbose_name='Color')),
                ('image', models.ImageField(default=0, upload_to='static')),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Nike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('color', models.CharField(max_length=200, verbose_name='Color')),
                ('image', models.ImageField(default=0, upload_to='static')),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
