# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0002_auto_20190510_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adidas',
            old_name='marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='converse',
            old_name='marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='nike',
            old_name='marca',
            new_name='brand',
        ),
    ]
