# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0003_auto_20190510_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adidas',
            new_name='Zapatillas_Adidas',
        ),
        migrations.RenameModel(
            old_name='Nike',
            new_name='Zapatillas_Converse',
        ),
        migrations.RenameModel(
            old_name='Converse',
            new_name='Zapatillas_Nike',
        ),
    ]
