# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0004_auto_20190511_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapatillas_Vans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=200, verbose_name='Marca')),
                ('color', models.CharField(max_length=200, verbose_name='Color')),
                ('image', models.ImageField(default=0, upload_to='static')),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
