# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0005_zapatillas_vans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zapatillas_Vans',
        ),
    ]
